# RAGFlow
#
# See:
# - https://github.com/infiniflow/ragflow
# - https://ragflow.io/docs/dev/build_docker_image
# - https://github.com/infiniflow/infinity

networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

# Add this to the ragflow service to allow access to ollama?
# extra_hosts:
#       - "host.docker.internal:host-gateway"

services:
  # Custom build RAGFlow for macos
  ragflow:
    # profile:
    #   - ragflow-macos # TODO: add additional profile to use image instead of building
    build:
      context: ${LLEMONSTACK_REPOS_PATH:-.}/ragflow
      dockerfile: Dockerfile
    container_name: ragflow
    ports:
      - ${RAGFLOW_HOST_API_PORT:-9380}:9380
      - ${RAGFLOW_HOST_PORT:-9390}:80
      - ${RAGFLOW_HOST_SSL_PORT:-9391}:443
      - ${RAGFLOW_HOST_MCP_PORT:-9382}:9382
      # Extra ports in docker-compose.yaml, not sure what they're for?
      # - 5678:5678
      # - 5679:5679
    volumes:
      - ${LLEMONSTACK_VOLUMES_PATH:-./volumes}/ragflow/logs:/ragflow/logs
      - ${LLEMONSTACK_REPOS_PATH:-.}/ragflow/docker/nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ${LLEMONSTACK_REPOS_PATH:-.}/ragflow/docker/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ${LLEMONSTACK_REPOS_PATH:-.}/ragflow/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./service_conf.template.yaml:/ragflow/conf/service_conf.yaml.template
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS:-0}
      - LIGHTEN=${RAGFLOW_IMAGE_LIGHTEN:-1}
    restart: on-failure

    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.

    # Allow ragflow to access host for ollama
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

    # Start ragflow with MCP server enabled
    # TODO: move to ragflow-mcp service
    # command:
    #   - --enable-mcpserver
    #   - --mcp-host=0.0.0.0
    #   - --mcp-port=9382
    #   - --mcp-base-url=http://127.0.0.1:9380
    #   - --mcp-script-path=/ragflow/mcp/server/server.py
    #   - --mcp-mode=self-host
    #   - --mcp-host-api-key=${RAGFLOW_MCP_API_KEY:-}

  # executor:
  #   build:
  #     context: ${LLEMONSTACK_REPOS_PATH:-.}/ragflow
  #     dockerfile: Dockerfile
  #   container_name: ragflow-executor
  #   volumes:
  #     - ./ragflow-logs:/ragflow/logs
  #     - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
  #   env_file: .env
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - HF_ENDPOINT=${HF_ENDPOINT}
  #     - MACOS=${MACOS}
  #   entrypoint: "/ragflow/entrypoint_task_executor.sh 1 3"
  #   networks:
  #     - ragflow
  #   restart: on-failure
  #   # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
  #   # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
