ragflow:
  host: 0.0.0.0
  http_port: 9380

minio:
  user: '${MINIO_USER:-minio}'
  password: '${MINIO_PASSWORD}'
  host: '${MINIO_HOST:-minio:9000}'

es:
  hosts: '${ELASTICSEARCH_HOST:-http://elasticsearch:9200}'
  username: '${ELASTICSEARCH_USER:-elastic}'
  password: '${ELASTICSEARCH_PASSWORD}'

redis:
  db: '${REDIS_DB:-1}'
  password: '${REDIS_PASSWORD}'
  host: '${REDIS_HOST:-redis:6379}'

postgres:
  name: '${POSTGRES_DB:-postgres}'
  user: '${POSTGRES_USER}'
  password: '${POSTGRES_PASSWORD}'
  host: '${POSTGRES_HOST:-postgres}'
  port: ${POSTGRES_PORT:-5432}
  max_connections: 100
  stale_timeout: 30

# user_default_llm:
#   factory: 'Tongyi-Qianwen'
#   api_key: 'sk-xxxxxxxxxxxxx'
#   base_url: ''
#   default_models:
#     chat_model: 'qwen-plus'
#     embedding_model: 'BAAI/bge-large-zh-v1.5@BAAI'
#     rerank_model: ''
#     asr_model: ''
#     image2text_model: ''

# oauth:
#   github:
#     client_id: xxxxxxxxxxxxxxxxxxxxxxxxx
#     secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     url: https://github.com/login/oauth/access_token
#   feishu:
#     app_id: cli_xxxxxxxxxxxxxxxxxxx
#     app_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     app_access_token_url: https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal
#     user_access_token_url: https://open.feishu.cn/open-apis/authen/v1/oidc/access_token
#     grant_type: 'authorization_code'

# authentication:
#   client:
#     switch: false
#     http_app_key:
#     http_secret_key:
#   site:
#     switch: false

# permission:
#   switch: false
#   component: false
#   dataset: false
